<Project>
  <PropertyGroup>
    <MeerkatRoot>$(MSBuildThisFileDirectory)</MeerkatRoot>
    <BaseOutputPath>$(MeerkatRoot)bin\</BaseOutputPath>
    <OutputPath>$(BaseOutputPath)</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <BaseIntermediateOutputPath>$(MeerkatRoot)build\obj\$(MSBuildProjectName)\</BaseIntermediateOutputPath>
    <MSBuildProjectExtensionsPath>$(BaseIntermediateOutputPath)</MSBuildProjectExtensionsPath>
  </PropertyGroup>
</Project>
