<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AssemblyName>IfcViewer</AssemblyName>
    <TargetExt>.gha</TargetExt>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <RhinoDir Condition="'$(RhinoDir)' == ''">C:\Program Files\Rhino 8</RhinoDir>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="RhinoCommon"><HintPath>$(RhinoDir)\System\RhinoCommon.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Grasshopper"><HintPath>$(RhinoDir)\Plug-ins\Grasshopper\Grasshopper.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="GH_IO"><HintPath>$(RhinoDir)\Plug-ins\Grasshopper\GH_IO.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Newtonsoft.Json"><HintPath>$(RhinoDir)\System\Newtonsoft.Json.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="System.Drawing"/>
    <Reference Include="System.Windows.Forms"/>
    <Reference Include="System.IO.Compression"/>
    <Reference Include="System.IO.Compression.FileSystem"/>
  </ItemGroup>
</Project>
